# Generated by Django 4.2.7 on 2024-02-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('images', models.ImageField(default=None, upload_to='images/products/')),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=225)),
                ('original_price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.sub_category')),
            ],
        ),
    ]
